TRUNCATE TABLE ebarrival;
TRUNCATE TABLE ebsales_ref;
TRUNCATE TABLE ebsales;
TRUNCATE TABLE ebreview;
TRUNCATE TABLE ebfavorite;
TRUNCATE TABLE ebcart;
ALTER TABLE ebcart DISABLE CONSTRAINTS fk_ebcart_book_isbn;
ALTER TABLE ebfavorite DISABLE CONSTRAINTS fk_ebfavorite_book_isbn;
ALTER TABLE ebreview DISABLE CONSTRAINTS fk_ebreview_book_isbn;
ALTER TABLE ebsales_ref DISABLE CONSTRAINTS fk_ebsales_ref_book_isbn;
TRUNCATE TABLE ebbook;
ALTER TABLE ebcart ENABLE CONSTRAINTS fk_ebcart_book_isbn;
ALTER TABLE ebfavorite ENABLE CONSTRAINTS fk_ebfavorite_book_isbn;
ALTER TABLE ebreview ENABLE CONSTRAINTS fk_ebreview_book_isbn;
ALTER TABLE ebsales_ref ENABLE CONSTRAINTS fk_ebsales_ref_book_isbn;
ALTER TABLE ebbook DISABLE CONSTRAINTS fk_ebbook_genre_id;
TRUNCATE TABLE ebgenre;
ALTER TABLE ebbook ENABLE CONSTRAINTS fk_ebbook_genre_id;
TRUNCATE TABLE ebcredit;
ALTER TABLE ebsales DISABLE CONSTRAINTS fk_ebsales_address_id;
TRUNCATE TABLE ebaddress;
ALTER TABLE ebsales ENABLE CONSTRAINTS fk_ebsales_address_id;
ALTER TABLE ebaddress DISABLE CONSTRAINTS fk_ebaddress_user_id;
ALTER TABLE ebcredit DISABLE CONSTRAINTS fk_ebcredit_user_id;
ALTER TABLE ebcart DISABLE CONSTRAINTS fk_ebcart_user_id;
ALTER TABLE ebfavorite DISABLE CONSTRAINTS fk_ebfavorite_user_id;
ALTER TABLE ebreview DISABLE CONSTRAINTS fk_ebreview_user_id;
ALTER TABLE ebsales DISABLE CONSTRAINTS fk_ebsales_user_id;
TRUNCATE TABLE ebuser;
ALTER TABLE ebaddress ENABLE CONSTRAINTS fk_ebaddress_user_id;
ALTER TABLE ebcredit ENABLE CONSTRAINTS fk_ebcredit_user_id;
ALTER TABLE ebcart ENABLE CONSTRAINTS fk_ebcart_user_id;
ALTER TABLE ebfavorite ENABLE CONSTRAINTS fk_ebfavorite_user_id;
ALTER TABLE ebreview ENABLE CONSTRAINTS fk_ebreview_user_id;
ALTER TABLE ebsales ENABLE CONSTRAINTS fk_ebsales_user_id;