OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBADDRESS_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBADDRESS"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"ADDRESS_ID" ,
"USER_ID" CHAR (30),
"RECEIVER_NAME" CHAR (100),
"POSTAL_CODE" ,
"ADDRESS" CHAR (150),
"TEL" CHAR (11))
