OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBCART_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBCART"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"USER_ID" CHAR (20),
"BOOK_ISBN" CHAR (13),
"CART_AMOUNT" )
