OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBCREDIT_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBCREDIT"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"USER_ID" CHAR (30),
"CARD_NAME" CHAR (30),
"CARD_NUMBER" CHAR (16),
"SECURITY_NUMBER" CHAR (3),
"CARD_EXPIRATION" CHAR (11))
