OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBREVIEW_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBREVIEW"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"BOOK_ISBN" CHAR (13),
"USER_ID" CHAR (30),
"REVIEW_TEXT" CHAR (4000),
"REVIEW_STAR" ,
"REVIEW_DATE" DATE "YYYY-MM-DD HH24:MI:SS" )
