OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'C:\ECbook\sql\ok\loader\ldr\EBSALES_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBSALES"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"SALES_ID" ,
"USER_ID" CHAR (30),
"SALES_DATE" DATE "YYYY-MM-DD HH24:MI:SS" ,
"ADDRESS_ID" ,
"PAY_METHOD" CHAR (100))
