OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBSALES_REF_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBSALES_REF"
FIELDS TERMINATED BY',|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"SALES_ID" ,
"BOOK_ISBN" CHAR (13),
"SALES_AMOUNT" )
