OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'EBUSER_DATA_TABLE.ldr' "str '\r\n'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "EBTEST"."EBUSER"
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"ID" CHAR (100),
"NAME" CHAR (100),
"PASS" CHAR (255),
"MAIL" CHAR (30),
"SEX" ,
"BIRTH" DATE "YYYY-MM-DD HH24:MI:SS" )
