DROP USER ebtest CASCADE;

CREATE USER ebtest
   IDENTIFIED BY ebpass
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA 100M ON USERS;
   
GRANT CREATE SESSION,CREATE TABLE,CREATE SEQUENCE,CREATE VIEW,CREATE ANY INDEX TO EBTEST;
exit
